### PR TITLE
Added first graph module + all prodigy recipes

### PR DESCRIPTION
**Pull request by SkanderSoltani**
- Created first EntityGraph  and Node classes.
- Run test with light example and plot results. 
- Added prodigy recipes to the repo

### CODE REVIEW

**Review by Eliotfrazier — COMMENTED** [review]
Good start, let's do a call together to review. 

A few features we need to add in, and a big consideration here will be storage, and query efficiency.

**Comment by SkanderSoltani** [comment]
Thank you for reviewing Eliot. Looking forward to a have some time with you. 

Skander

**Comment by Eliotfrazier** [comment]
@SkanderSoltani shall I close this now? I'm guessing we've replaced much of this since we didn't merge.

**Comment by SkanderSoltani** [comment]
Hi Eliot,
Yes please, I will keep the code saved on my machine just in case.


Skander Soltani

**Comment by Eliotfrazier** [comment]
@SkanderSoltani  Ok, please remember to get everything committed by the end of the week :).

**Pull request closed without merging**
